{
 "title": "NYC Taxi - Unified Dashboard",
 "tags": [
  "taxi",
  "unified"
 ],
 "time": { "from": "2025-08-01T00:00:00.000Z", "to": "2025-08-01T23:59:59.000Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Top 10 Zones by Total Revenue",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT zone, SUM(total_revenue) AS total_revenue_sum FROM analytics.zones_revenue_by_window WHERE time_bucket >= $__from AND time_bucket <= $__to GROUP BY zone ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Total Trip Demand by Zone",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "SELECT zone, sum(trip_count) as total_trips FROM analytics.trip_demand_by_zone_5m WHERE time_bucket >= $__from AND time_bucket <= $__to GROUP BY zone ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Average Fare Per Mile by Borough",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "target": "SELECT borough, SUM(total_revenue) AS total_revenue_sum, SUM(total_distance) AS total_distance_sum FROM analytics.borough_fare_distance WHERE time_bucket >= $__from AND time_bucket <= $__to GROUP BY borough ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Average Speed (mph) by Borough",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "target": "SELECT borough, time_bucket, total_distance, total_duration_seconds FROM analytics.borough_avg_speed WHERE time_bucket >= $__from AND time_bucket <= $__to ALLOW FILTERING"
    }
   ]
  }
 ]
}